### ISSUE TITLE
TypeError: Cannot read property 'expression' of null

### ISSUE THREAD

**Issue by dbkaplun** [gunar/callgraph#15]
```
TypeError: Cannot read property 'expression' of null
    at TreeWalker.visit (/usr/local/lib/node_modules/callgraph/parser.js:50:41)
    at TreeWalker._visit (eval at <anonymous> (/usr/local/lib/node_modules/callgraph/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1339:24)
    at AST_Var._walk (eval at <anonymous> (/usr/local/lib/node_modules/callgraph/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:929:24)
    at AST_ForIn.eval (eval at <anonymous> (/usr/local/lib/node_modules/callgraph/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:654:23)
    at TreeWalker._visit (eval at <anonymous> (/usr/local/lib/node_modules/callgraph/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1343:21)
    at AST_ForIn._walk (eval at <anonymous> (/usr/local/lib/node_modules/callgraph/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:653:24)
    at walk_body (eval at <anonymous> (/usr/local/lib/node_modules/callgraph/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:530:17)
    at AST_BlockStatement.eval (eval at <anonymous> (/usr/local/lib/node_modules/callgraph/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:541:13)
    at TreeWalker._visit (eval at <anonymous> (/usr/local/lib/node_modules/callgraph/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:1343:21)
    at AST_BlockStatement._walk (eval at <anonymous> (/usr/local/lib/node_modules/callgraph/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:540:24)
```
Using `npm install -g gunar/callgraph`

**Comment by gunar** [comment]
Solved by #17
